version: "3"
services:
  api:
    image: kc-docker1.kcell.kz:5000/upsbrowser_ws_api
    labels:
      kz.kcell.eit.business-service: "SharePoint"
      kz.kcell.eit.it-service: "SM"
      kz.kcell.eit.subsystem: "UPSBrowser"
      kz.kcell.eit.production-status: "production"
    logging:
      driver: "json-file"
      options:
        labels: "com.docker.stack.namespace,com.docker.swarm.node.id,com.docker.swarm.service.id,com.docker.swarm.service.name,com.docker.swarm.task.id,kz.kcell.eit.business-service,kz.kcell.eit.it-service,kz.kcell.eit.subsystem,kz.kcell.eit.production-status"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4003:8080"
    networks:
      - upsbrowser_ws_net
networks:
  upsbrowser_ws_net:
